### ISSUE TITLE
Perhaps intentional, confusing nonetheless

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/sql-create-tables-lab#1]
In the table at the bottom of the readme some of the types are not supported by sqlite3.  The docs for sqlite3 say you can't limit the amount of characters in a TEXT type (see gender).  Also, boolean values are only represented in the INTEGER type.

While this is easy to figure out by reading through the data types on the docs, perhaps a hint is needed to do this research?

If your thinking "no, the student should be discovering how they need to do research on their own" then I would argue that in the previous lab it tells us not to worry about the other datatypes yet and to just keep going. Sort of insinuating to not get distracted by the docs...

**Comment by AnnJohn** [comment]
Icebox for now
